### ISSUE TITLE
Support Symfony 7

### ISSUE THREAD

**Issue by tacman** [tzunghaor/settings-bundle#10]
Symfony 7 is in beta.

There are a few deprecations, mostly involving return types.

What do you think of a new release that only supports ^6.3|^7.0 (since the earlier versions of 6 are no longer supported), and bumping the minimum PHP to match Symfony?  One advantage to this approach is simplifying the bundle configuration.

I think bumping to Symfony 7 won't be too hard even supporting 5.4.  I can make a PR if you'd like.

**Comment by tzunghaor** [comment]
Hi. First sorry for responding so late.

Yes, I want to drop support for older versions, especially PHP 7 support and annotations (WIP is already in master), I will then update the Symfony support too. But it probably won't happen this year.

**Comment by tzunghaor** [comment]
Added Symfony support in release 0.15
